### ISSUE TITLE
Define a clear brand name

### ISSUE THREAD

**Issue by seguri** [moturus/motor-os#4]
> Motūrus OS (sometimes called Motor OS)

I think this confusion should be avoided and a clear name should be established. Motūrus OS, Motor OS, motor-os, motorOS... Just stick with one and use that everywhere, including the Licenses.

My 2 cents!

✌️

**Comment by lasiotus** [comment]
Thanks for the suggestion! I'm more focused on actual features/performance at the moment, but branding definitely will have to be addressed at some point. I kinda like "Motūrus OS", but I'm not sure the name will stick vs "Motor OS"... Let's see how it goes. :)

**Comment by lasiotus** [comment]
So now the OS is "Motor OS", and "Motūrus project" is similar to "Microsoft Longhorn". Is this clear(er)? :)
