### ISSUE TITLE
Question, booting Motor-OS on hardware?

### ISSUE THREAD

**Issue by stevenanthonyrevo** [moturus/motor-os#9]
Hi @lasiotus, 

Is it possible to create a bootable .ISO script for x86_64 hardware? 

I don't have much rust experience but I seen a post about [creating the ISO](https://os.phil-opp.com/multiboot-kernel/). 

It looks like `grub-mkrescue -o os.iso isofiles` can help create the ISO but I'd need more help with booting. 

Thanks!

**Comment by lasiotus** [comment]
No, Motor OS won't boot on real hardware, it needs virtio devices and kvm. You should look into Redox or blog_os if you want a Rust-based OS that boots on real HW.

**Comment by lasiotus** [comment]
Moturus OS is designed to run in VMs.
